log:
  trace: ./log/trace
server:
  port: 1337
auth:
  strategy: secret
  algorithm: sha256
  encryption: aes256
  encoding: base64
  users:
test:
  loglevel: fatal
  users:
    tony-the-tester: "They are grrrrreat! I swear, for real okay."
