log:
  trace: ./log/trace
server:
  port: 1337
auth:
  strategy: secret
  algorithm: sha256
  encryption: aes256
  encoding: base64
  jwt:
    maxExpiryTimeMS: 31536000000 # 1000×60×60×24×365=1 Year
  users:
test:
  loglevel: fatal
  users:
    tony-the-tester: "They are grrrrreat! I swear, for real okay."
